#!/bin/bash

source util.sh

echo "KATA 1 - STASHING FILES

SCENARIO DESCRIPTION:
You made local changes to some files. Stash your local changes,
then pull remote changes (with a --rebase). After that, unstash the change,
commit and push it.

GOAL:
- Get upstream commits
- Commit and push your changes on top of them

LEARNINGS:
- Common git workflow"

commitWithJohnny src/johnny.js "I am johnny 5" "Johnny's commit"
appendToFile src/app.js "Old MACDONALD had a farm"
appendToFile src/app.js "E-I-E-I-O"
